[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PRESERVE_WEBPACK_CACHE = "true"
  NEXT_SHARP_PATH = "/opt/build/repo/node_modules/sharp"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"  # Updated for dynamic deployment

# Needed for dynamic deployment
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

# Set cache headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Handle remote images
[images]
  remote_images = [
    "https://same-assets.com/*",
    "https://ext.same-assets.com/*"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
